version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cardealershipdb
    ports:
      - "3306:3306"
    volumes:
      - ./database_backup.sql:/docker-entrypoint-initdb.d/database_backup.sql
